package practicafinaldein;

/**
 * @date 2 feb. 2022
 * @author Jhoan López
 * @email Jhoanlopezclase@gmail.com
 */

public class AprobadoPantallaB extends javax.swing.JFrame {

    /**
     * Creates new form BienvenidosPantalla
     */
    public AprobadoPantallaB() {
        initComponents();
        AsignarImagen asignarImg = new AsignarImagen();
        resultado = (String) TestCarnetB.aprobadoSuspendidoB.get(1);
        res = (String) TestCarnetB.aprobadoSuspendidoB.get(2);
        jl_informacion.setText(resultado);
        
        if (res.equalsIgnoreCase("aprobado")) {
           asignarImg.asignarImagenes("ExamenAprobado.png", jl_categoriaElegida); 
        } else {
           asignarImg.asignarImagenes("ExamenSuspendido.png", jl_categoriaElegida);  
        }
    }
    
    static String resultado;
    static String res;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_fondoFrame = new javax.swing.JPanel();
        jl_categoriaElegida = new javax.swing.JLabel();
        jb_elegirCategoria = new javax.swing.JButton();
        jb_hacerOtroTest = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jl_minimizar = new javax.swing.JLabel();
        jl_cerrar = new javax.swing.JLabel();
        jl_informacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_fondoFrame.setBackground(new java.awt.Color(248, 249, 249));
        jp_fondoFrame.setPreferredSize(new java.awt.Dimension(1200, 600));

        jl_categoriaElegida.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jl_categoriaElegida.setForeground(new java.awt.Color(51, 51, 51));
        jl_categoriaElegida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_categoriaElegida.setMaximumSize(new java.awt.Dimension(610, 55));
        jl_categoriaElegida.setMinimumSize(new java.awt.Dimension(610, 55));
        jl_categoriaElegida.setName(""); // NOI18N
        jl_categoriaElegida.setPreferredSize(new java.awt.Dimension(500, 70));

        jb_elegirCategoria.setBackground(new java.awt.Color(129, 199, 132));
        jb_elegirCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_elegirCategoria.setForeground(new java.awt.Color(80, 80, 80));
        jb_elegirCategoria.setText("ELEGIR CATEGORIA");
        jb_elegirCategoria.setBorder(null);
        jb_elegirCategoria.setBorderPainted(false);
        jb_elegirCategoria.setMaximumSize(new java.awt.Dimension(200, 50));
        jb_elegirCategoria.setMinimumSize(new java.awt.Dimension(200, 50));
        jb_elegirCategoria.setName(""); // NOI18N
        jb_elegirCategoria.setPreferredSize(new java.awt.Dimension(400, 75));
        jb_elegirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_elegirCategoriaActionPerformed(evt);
            }
        });

        jb_hacerOtroTest.setBackground(new java.awt.Color(129, 212, 250));
        jb_hacerOtroTest.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_hacerOtroTest.setForeground(new java.awt.Color(80, 80, 80));
        jb_hacerOtroTest.setText("HACER OTRO TEST");
        jb_hacerOtroTest.setBorder(null);
        jb_hacerOtroTest.setBorderPainted(false);
        jb_hacerOtroTest.setMaximumSize(new java.awt.Dimension(200, 50));
        jb_hacerOtroTest.setMinimumSize(new java.awt.Dimension(200, 50));
        jb_hacerOtroTest.setName(""); // NOI18N
        jb_hacerOtroTest.setPreferredSize(new java.awt.Dimension(400, 75));
        jb_hacerOtroTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_hacerOtroTestActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(248, 249, 249));

        jl_minimizar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jl_minimizar.setForeground(new java.awt.Color(153, 153, 153));
        jl_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_minimizar.setText("-");
        jl_minimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jl_minimizar.setMaximumSize(new java.awt.Dimension(25, 25));
        jl_minimizar.setMinimumSize(new java.awt.Dimension(25, 25));
        jl_minimizar.setPreferredSize(new java.awt.Dimension(25, 25));
        jl_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_minimizarMouseClicked(evt);
            }
        });

        jl_cerrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jl_cerrar.setForeground(new java.awt.Color(153, 153, 153));
        jl_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_cerrar.setText("X");
        jl_cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jl_cerrar.setMaximumSize(new java.awt.Dimension(25, 25));
        jl_cerrar.setMinimumSize(new java.awt.Dimension(25, 25));
        jl_cerrar.setPreferredSize(new java.awt.Dimension(25, 25));
        jl_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_cerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jl_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jl_informacion.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jl_informacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_informacion.setText("jLabel1");

        javax.swing.GroupLayout jp_fondoFrameLayout = new javax.swing.GroupLayout(jp_fondoFrame);
        jp_fondoFrame.setLayout(jp_fondoFrameLayout);
        jp_fondoFrameLayout.setHorizontalGroup(
            jp_fondoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_fondoFrameLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jl_categoriaElegida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_fondoFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_fondoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_fondoFrameLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_fondoFrameLayout.createSequentialGroup()
                        .addGroup(jp_fondoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_informacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_fondoFrameLayout.createSequentialGroup()
                                .addComponent(jb_elegirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jb_hacerOtroTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(159, 159, 159))))
        );
        jp_fondoFrameLayout.setVerticalGroup(
            jp_fondoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_fondoFrameLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jl_categoriaElegida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jl_informacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addGroup(jp_fondoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_hacerOtroTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_elegirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        getContentPane().add(jp_fondoFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_elegirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_elegirCategoriaActionPerformed
        LlamadaDeClases pantalla = new LlamadaDeClases();
        TestCarnetB.aprobadoSuspendidoB.clear();
        pantalla.elegirCategoria(this);
        
    }//GEN-LAST:event_jb_elegirCategoriaActionPerformed

    private void jl_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_minimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jl_minimizarMouseClicked

    private void jl_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jl_cerrarMouseClicked

    private void jb_hacerOtroTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_hacerOtroTestActionPerformed
        LlamadaDeClases pantalla = new LlamadaDeClases();
        TestCarnetB.aprobadoSuspendidoB.clear();
        pantalla.carnetAPantalla(this);
        
    }//GEN-LAST:event_jb_hacerOtroTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AprobadoPantallaB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AprobadoPantallaB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AprobadoPantallaB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AprobadoPantallaB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>



        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AprobadoPantallaB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jb_elegirCategoria;
    private javax.swing.JButton jb_hacerOtroTest;
    private javax.swing.JLabel jl_categoriaElegida;
    private javax.swing.JLabel jl_cerrar;
    private javax.swing.JLabel jl_informacion;
    private javax.swing.JLabel jl_minimizar;
    private javax.swing.JPanel jp_fondoFrame;
    // End of variables declaration//GEN-END:variables
}
